app:
  name: entregas_rutina   

paths:
  input: "data/raw/entregas.csv"
  output_base: "data/processed"

filters:
  start_date: "2025-01-01"
  end_date: "2025-12-31"
  country: ""

units:
  base_unit: "ST"
  cs_to_st_factor: 20           

delivery_types:
  routine: ["ZPRE", "ZVE1"]
  bonus: ["Z04", "Z05"]

dq:
  drop_duplicates: true
  dedup_keys: ["fecha_proceso", "pais", "material", "tipo_entrega","transporte","ruta","cantidad"]
  remove_nulls_in:
    - fecha_proceso
    - pais
    - material
    - cantidad
    - transporte
    - ruta
  valid_units: ["CS", "ST"]
  valid_delivery_types: ["ZPRE", "ZVE1", "Z04", "Z05"]
